nelmio_api_doc: ~

nelmio_cors:
    paths:
        '^/api/':
            allow_credentials: true
            allow_origin: ['*']
            allow_headers: ['Origin', 'X-Requested-With', 'Content-Type', 'Accept', 'apikey']
            allow_methods: ['POST','GET','DELETE','PUT']
            expose_headers: []
            max_age: 3600