fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

brd4_message:
    resource: "@Brd4MessageBundle/Resources/config/routing.yml"

brd4_user:
    resource: "@Brd4UserBundle/Resources/config/routing.yml"
    prefix:   /user

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

brd4_api:
    type: rest
    resource: "api.yml"
    prefix:   /api
