parameters:
    sleepness.shifter.class: Sleepness\Shifter

services:
    sleepness.shifter:
        class: %sleepness.shifter.class%

#    jms_serializer.object_constructor:
#        alias: jms_serializer.doctrine_object_constructor
#        public: false
#
#    jms_serializer.naming_strategy:
#        class: 'JMS\Serializer\Naming\IdenticalPropertyNamingStrategy'