Brd4\CommonBundle\Model\Credential:
    exclusion_policy: All
    properties:
        username:
            expose: true
            type: string
        password:
            expose: true
            type: string