brd4_message_add:
    path:     /message/add
    defaults: { _controller: Brd4MessageBundle:Message:add }

brd4_message_user_list:
    path:     /user/{id}/message/list/{page}
    defaults: { _controller: Brd4MessageBundle:Message:userList, page: 1 }
    requirements:
        id: \d+
        page: \d+

brd4_message_search:
    path:     /message/search/{page}
    defaults: { _controller: Brd4MessageBundle:Message:search, page: 1 }
    requirements:
        page: \d+

brd4_message_followers_message_list:
    path:     /{page}
    defaults: { _controller: Brd4MessageBundle:Message:followerList, page: 1 }
    requirements:
        page: \d+