Brd4\MessageBundle\Model\Message:
    exclusion_policy: All
    properties:
        id:
            expose: true
        text:
            expose: true
            type: string
        createdAt:
            expose: true
        user:
            expose: true
            type: Brd4\UserBundle\Model\User