Brd4\UserBundle\Model\Profile:
    exclusion_policy: All
    properties:
        email:
            type: string
            expose: true
        username:
            type: string
            expose: true
        password:
            type: string
            expose: true