brd4_user_list:
    path:     /list/{page}
    defaults: { _controller: Brd4UserBundle:User:list, page: 1 }
    requirements:
        _method: GET
        page: \d+

brd4_user_follow:
    path:     /follow/{id}
    defaults: { _controller: Brd4UserBundle:User:follow }
    requirements:
        id: \d+

brd4_user_followers:
    path:     /followers
    defaults: { _controller: Brd4UserBundle:User:followerList }